name: 'rust-cargo-make'
description: 'Install cargo-make by download the executable (faster than `cargo install cargo-make`)'
author: 'davidB'
inputs:
  version:              # change this
    description: 'version of cargo-make to install'
    default: '0.22.2'
runs:
  using: 'node12'
  main: 'lib/main.js'
