name: "test"
on:
  pull_request:
  push:
    branches:
      - master
      - "releases/*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm run build
      - run: npm test
  integration-test:
    runs-on: ${{ matrix.os.imageName }}
    strategy:
      matrix:
        rust_toolchain: ["stable"]
        os:
          - imageName: ubuntu-18.04
            target: x86_64-unknown-linux-gnu
            profile: linux
          # - imageName: 'macOS-10.14'
          #   target: x86_64-apple-darwin
          #   profile: mac
          - imageName: "windows-2019"
            target: x86_64-pc-windows-msvc
            profile: windows
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust_toolchain }}
          override: true
      - uses: davidB/rust-cargo-make@v1
      # - uses: actions/checkout@v1
      # - run: npm ci
      # - run: npm run build
      # - uses: ./
      # - run:
      - run: cargo make --version
